import {StyleSheet} from 'react-native';
import {BaseColor} from '@config';
import * as Utils from '@utils';

export default StyleSheet.create({
  homeContainer: {
    paddingHorizontal: 10,
  },
  imageBackground: {
    height: 140,
    width: '100%',
    position: 'absolute',
  },
  searchForm: {
    paddingTop: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: BaseColor.fieldColor,
    backgroundColor: BaseColor.MainPrimaryColor,
    shadowColor: 'black',
    shadowOffset: {width: 1.5, height: 1.5},
    shadowOpacity: 0.3,
    shadowRadius: 1,
    elevation: 1,
  },
  contentServiceIcon: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  contentCartPromotion: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  btnPromotion: {
    height: 30,
    borderRadius: 3,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  contentHiking: {
    marginTop: 20,
    marginLeft: 20,
    marginBottom: 10,
  },
  promotionBanner: {
    height: Utils.scaleWithPixel(100),
    width: '100%',
    marginTop: 10,
  },
  line: {
    height: 1,
    backgroundColor: BaseColor.textSecondaryColor,
    marginTop: 10,
    marginBottom: 20,
  },
  iconContent: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: BaseColor.SecondPrimaryColor,
  },
  itemService: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingTop: 3,
  },
  keyService: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingTop: 3,
  },
  specVoucherItem: {
    borderRadius: 8,
    backgroundColor: BaseColor.MainColor,
    width: Utils.scaleWithPixel(170),
    height: Utils.scaleWithPixel(260),
  },
  tourItem: {
    borderRadius: 8,
    width: Utils.scaleWithPixel(135),
    height: Utils.scaleWithPixel(160),
  },
  textInput: {
    height: 46,
    backgroundColor: BaseColor.MainColor,
    borderRadius: 5,
    padding: 10,
    width: '100%',
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  searchInput: {
    height: 45,
    backgroundColor: BaseColor.whiteColor,
    borderRadius: 4,
    padding: 10,
    width: '100%',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
  },
  keySection: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 30,
  },
  iconSection: {
    backgroundColor: BaseColor.MainPrimaryColor,
    marginTop: 10,
    paddingTop: 3,
    paddingBottom: 3,
    width: '100%',
  },
  keyStyleSection: {
    backgroundColor: BaseColor.MainPrimaryColor,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    marginTop: 10,
    paddingTop: 3,
    paddingBottom: 3,
    width: '100%',
  },
  categorySection: {
    alignItems: 'center',
    justifyContent: 'center',
    width: Utils.scaleWithPixel(55),
    height: Utils.scaleWithPixel(80),
  },
  iconCategoryContent: {
    flex: 1,
    flexDirection: 'column',
  },
  categoryName: {
    textAlign: 'center',
    marginTop: 10,
  },
  itemBrands: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    height: Utils.scaleWithPixel(50),
    backgroundColor: BaseColor.whiteColor,
    borderRadius: 7,
  },
  dotStyle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginHorizontal: 0,
    padding: 0,
    margin: 0,
    backgroundColor: 'rgba(128, 128, 128, 0.92)',
  },
  paginationBoxStyle: {
    position: 'absolute',
    bottom: 0,
    padding: 0,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  exploreCategory: {
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: BaseColor.fieldColor,
    backgroundColor: BaseColor.fieldColor,
    width: '95%',
    shadowColor: 'black',
    shadowOffset: {width: 1.5, height: 1.5},
    shadowOpacity: 0.3,
    shadowRadius: 1,
    elevation: 1,
    alignItems: 'center',
  },
  homeTitle: {
    marginVertical: 10,
  },
  promotionItem: {
    borderRadius: 8,
  },
  backOpacity: {
    position: 'absolute',
    backgroundColor: BaseColor.whiteColor,
    padding: 7,
    width: '100%',
    opacity: 0.5,
    bottom: 0,
    height: '100%',
  },
});
